type: app
description: Template to create a new repository with some Github default and Actions files
# template used to create the project
template: github-stack/new-repository
inputs:
  project_name: my-new-awesome-project
# list of plugins to be applied after project creation
plugins:
  - plugin: github-stack/issue-templates
  - plugin: github-stack/pull-request-template
  - plugin: github-stack/gha-first-interaction
  - plugin: github-stack/gha-auto-assign
  - plugin: github-stack/gha-horusec
  - plugin: github-stack/gha-gitleaks
  - plugin: github-stack/gha-super-linter
