---

extends: default

rules:
  braces:
    level: warning
    max-spaces-inside: 1
  brackets:
    level: warning
    max-spaces-inside: 1
  colons:
    level: warning
  commas:
    level: warning
  comments: disable
  comments-indentation: disable
  document-start: disable
  empty-lines:
    level: warning
  hyphens:
    level: warning
  indentation:
    level: warning
    indent-sequences: consistent
  line-length:
    level: warning
    allow-non-breakable-inline-mappings: true
  truthy: disable

# YAML files in those folders use Jinja and may not respect the commum yaml language
ignore: |
  gha-auto-assign/templates/
  gha-first-interaction/templates/
  gha-gitleaks/templates/
  gha-horusec/templates/
  gha-super-linter/templates/