name: gha-gitleaks
description: Plugin to add a gitleaks GitHub actions workflow
display-name: gha-gitleaks
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - GitHub
about: docs/about.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - "GitHub Actions"
types:
  - app
