name: create-repo
description: Task to create a remote GitHub repository
inputs:
  - label: GitHub Personal Access Token (PAT)
    type: password
    name: personal_access_token
    required: 'true'
  - label: Repository Name
    type: text
    name: github_repository_name
    required: 'true'
  - label: Is it a private repo?
    type: text
    name: private
    items:
      - 'yes'
      - 'no'
    required: 'true'
  - label: Clone the repository to current path?
    type: text
    name: clone
    items:
      - 'yes'
      - 'no'
    required: 'true'
supported-os:
  - windows
  - linux
  - mac
requirements-check:
  python3-dependency:
    check-command: python3 --version
    info: python3 is not installed
  pip-dependency:
    check-command: pip --version
    info: pip is not installed
command:
  windows: |
        pip install -r "{{ component_path }}\scripts\requirements.txt" --user --quiet
        python3 "{{ component_path }}\scripts\create_repo.py" {{ personal_access_token }} {{ github_repository_name }} {{ private }} {{ clone }}
  linux: |
        pip install -r "{{ component_path }}/scripts/requirements.txt" --user --quiet
        python3 "{{ component_path }}/scripts/create_repo.py" {{ personal_access_token }} {{ github_repository_name }} {{ private }} {{ clone }}
  mac: |
        pip install -r "{{ component_path }}/scripts/requirements.txt" --user --quiet
        python3 "{{ component_path }}/scripts/create_repo.py" {{ personal_access_token }} {{ github_repository_name }} {{ private }} {{ clone }}