name: First Interaction

on:
  pull_request:
  issues:
    types: opened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: {{ '${{ secrets.GITHUB_TOKEN }}' }}
          issue-message: "{{issue_message}}"
          pr-message: "{{pr_message}}"