name: new-repository
description: Plugin to create a new GitHub repository
display-name: new-repository
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - GitHub
about: docs/about.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - "Github"
types:
  - app
inputs:
  - label: Project name
    type: text
    name: project_name
    default: project-name
global-computed-inputs:
  project_name_sanitized: "{{inputs.project_name|replace(' ', '-')|lower}}"
